### ISSUE TITLE
ImportError: No module named 'yaml'

### ISSUE THREAD

**Issue by tuonan** [ros/urdf_tutorial#37]
I operate step by step, following < http://stevenshi.me/2017/07/08/ros-primary-tutorial-17 >
When I use command <   roslaunch urdf_tutorial display.launch model:=urdf/01-myfirst.urdf >, failed.
started core service [/rosout]
process[joint_state_publisher-2]: started with pid [7172]
process[robot_state_publisher-3]: started with pid [7177]
process[rviz-4]: started with pid [7178]
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/joint_state_publisher/joint_state_publisher", line 3, in <module>
    import rospy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/melodic/lib/python2.7/dist-packages/std_msgs/msg/__init__.py", line 1, in <module>
    from ._Bool import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/std_msgs/msg/_Bool.py", line 5, in <module>
    import genpy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genpy/message.py", line 44, in <module>
    import yaml
ImportError: No module named 'yaml'
[joint_state_publisher-2] process has died [pid 7172, exit code 1, cmd /opt/ros/melodic/lib/joint_state_publisher/joint_state_publisher __name:=joint_state_publisher __log:=/home/lily/.ros/log/ff648b1c-8c68-11e9-95b8-6014b3858129/joint_state_publisher-2.log].
log file: /home/lily/.ros/log/ff648b1c-8c68-11e9-95b8-6014b3858129/joint_state_publisher-2*.log

**Comment by DLu** [comment]
It looks like your system is missing basic Python dependencies. Please open up a ticket on `answers.ros.org` for more help.
